name: fun-with-triangles

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "15.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  fwt:
    type: tool
    platform: macOS
    sources:
        - path: etc/
          type: folder
        - path: build/
          type: folder
        - path: Makefile
        - path: project.yml
        - path: README.md
        - path: scenes/config.h
        - path: src/
        - path: deps/
          type: folder
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
        - sdk: CoreServices.framework
        - sdk: CoreFoundation.framework
        - sdk: IOKit.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps, $(PROJECT_DIR)/scenes]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fno-objc-arc]
  test:
    type: library.dynamic
    platform: macOS
    sources:
        - path: scenes/test.c
        - path: src/
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps, $(PROJECT_DIR)/scenes]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fno-objc-arc, -DSOKOL_NO_ENTRY, -DLURK_SCENE]
